"""
Captain Raccoon — Story Engine
Uses Claude API to generate complete episode scripts with scene breakdowns.
"""
from __future__ import annotations

import json
import random
from dataclasses import dataclass, field
from typing import Optional

import anthropic
import structlog

from captain_raccoon.config.settings import get_character, get_settings
from captain_raccoon.monitoring.setup import track_metric, capture_exception
from captain_raccoon.utils.retry import with_retry

log = structlog.get_logger(__name__)


# =============================================================================
# DATA MODELS
# =============================================================================
@dataclass
class Scene:
    """A single visual scene within an episode."""
    scene_number: int
    title: str
    narration: str                  # Words Captain Raccoon speaks
    visual_description: str         # What the viewer sees (for image/video prompts)
    emotion: str                    # dominant_emotion: happy | sad | tense | calm | funny
    duration_seconds: float         # Estimated duration based on word count
    setting: str                    # Where this scene takes place
    action: str                     # What Cap is doing physically


@dataclass
class EpisodeScript:
    """Complete episode script generated by Claude."""
    title: str
    logline: str                    # One sentence hook
    theme: str                      # Which content pillar this addresses
    hook: str                       # First 3 seconds — must grab attention
    scenes: list[Scene]
    call_to_action: str             # Soft CTA at the end
    hashtags: list[str]
    youtube_title: str
    youtube_description: str
    instagram_caption: str
    total_duration_seconds: float
    word_count: int
    raw_response: str = field(default="", repr=False)

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "logline": self.logline,
            "theme": self.theme,
            "hook": self.hook,
            "scenes": [
                {
                    "scene_number": s.scene_number,
                    "title": s.title,
                    "narration": s.narration,
                    "visual_description": s.visual_description,
                    "emotion": s.emotion,
                    "duration_seconds": s.duration_seconds,
                    "setting": s.setting,
                    "action": s.action,
                }
                for s in self.scenes
            ],
            "call_to_action": self.call_to_action,
            "hashtags": self.hashtags,
            "youtube_title": self.youtube_title,
            "youtube_description": self.youtube_description,
            "instagram_caption": self.instagram_caption,
            "total_duration_seconds": self.total_duration_seconds,
            "word_count": self.word_count,
        }


# =============================================================================
# STORY ENGINE
# =============================================================================
class StoryEngine:
    """
    Generates complete Captain Raccoon episode scripts using Claude API.
    Supports topic suggestions, theme targeting, and full fallback handling.
    """

    SCRIPT_SCHEMA = """
Return a valid JSON object with EXACTLY this structure:
{
  "title": "Short punchy episode title",
  "logline": "One sentence that makes someone stop scrolling",
  "theme": "Which content pillar this addresses",
  "hook": "First 3 seconds of narration — the attention-grabber",
  "scenes": [
    {
      "scene_number": 1,
      "title": "Scene name",
      "narration": "Exact words Captain Raccoon speaks. Conversational, warm, punchy.",
      "visual_description": "Cinematic description of what the viewer sees — setting, lighting, action, mood. Be specific. No character name, describe him as 'a raccoon in an aviator jacket'.",
      "emotion": "happy|sad|tense|calm|funny|determined|reflective",
      "setting": "Location name from the world (or a new vivid one)",
      "action": "Physical action Cap is doing in this scene"
    }
  ],
  "call_to_action": "Soft, non-pushy closing line from Cap (NOT 'subscribe')",
  "hashtags": ["CaptainRaccoon", "motivation", ...],
  "youtube_title": "SEO-optimized title under 70 chars with emoji",
  "youtube_description": "3-4 sentence video description with keywords",
  "instagram_caption": "Punchy caption under 150 chars with 3-5 hashtags"
}
"""

    def __init__(self):
        self._settings = get_settings()
        self._character = get_character()
        self._client = anthropic.Anthropic(api_key=self._settings.anthropic_api_key)
        self._system_prompt = self._character.build_character_system_prompt()

    # ─────────────────────────────────────────────────────────────────────────
    # PUBLIC API
    # ─────────────────────────────────────────────────────────────────────────
    def generate(
        self,
        topic: Optional[str] = None,
        theme: Optional[str] = None,
        scene_count: Optional[int] = None,
    ) -> EpisodeScript:
        """
        Generate a complete episode script.

        Args:
            topic:  Optional free-text topic hint (e.g. "dealing with failure")
            theme:  Optional content pillar override
            scene_count: Override default scene count (4–7)
        """
        if topic is None:
            topic = self._pick_random_topic()
        if theme is None:
            theme = random.choice(self._character.content_pillars)
        if scene_count is None:
            fmt = self._character.episode_format
            scene_count = random.randint(
                fmt.get("scene_count_min", 4),
                fmt.get("scene_count_max", 7),
            )

        log.info(
            "story_engine.generating",
            topic=topic,
            theme=theme,
            scene_count=scene_count,
        )

        user_prompt = self._build_user_prompt(topic, theme, scene_count)

        try:
            raw = self._call_claude(user_prompt, model=self._settings.claude_model)
        except Exception as e:
            log.warning("story_engine.primary_failed", error=str(e))
            capture_exception(e)
            # Fallback to haiku
            raw = self._call_claude(
                user_prompt, model=self._settings.claude_fallback_model
            )

        script = self._parse_response(raw)
        track_metric("story_engine.episode_generated", 1, tags={"theme": theme})
        log.info(
            "story_engine.done",
            title=script.title,
            scenes=len(script.scenes),
            duration=script.total_duration_seconds,
        )
        return script

    def generate_batch(self, count: int = 5) -> list[EpisodeScript]:
        """Generate multiple episodes covering different themes."""
        scripts = []
        pillars = self._character.content_pillars
        for i in range(count):
            theme = pillars[i % len(pillars)]
            try:
                scripts.append(self.generate(theme=theme))
            except Exception as e:
                log.error("story_engine.batch_item_failed", index=i, error=str(e))
                capture_exception(e)
        return scripts

    # ─────────────────────────────────────────────────────────────────────────
    # PRIVATE HELPERS
    # ─────────────────────────────────────────────────────────────────────────
    @with_retry(max_attempts=3)
    def _call_claude(self, user_prompt: str, model: str) -> str:
        fmt = self._character.episode_format
        target_seconds = fmt.get("target_duration_seconds", 60)
        wpm = fmt.get("words_per_minute", 140)
        target_words = int((target_seconds / 60) * wpm)

        response = self._client.messages.create(
            model=model,
            max_tokens=4096,
            system=self._system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": f"{user_prompt}\n\nTarget total narration: ~{target_words} words across all scenes combined.\n\n{self.SCRIPT_SCHEMA}",
                }
            ],
        )
        return response.content[0].text

    def _build_user_prompt(self, topic: str, theme: str, scene_count: int) -> str:
        return f"""Write a complete Captain Raccoon episode script.

TOPIC: {topic}
THEME (content pillar): {theme}
NUMBER OF SCENES: {scene_count}

The episode should:
1. Open with a hook that makes someone stop scrolling in 3 seconds
2. Tell a specific, grounded story (not generic advice)
3. Use THE SPRAWL world naturally — mention real locations, other animal citizens
4. Have emotional variety across scenes (don't stay in one mood)
5. End with genuine warmth and a soft nudge — never a hard sell

Make it feel like Captain Raccoon is sitting across from the viewer sharing a real moment from his life.
"""

    def _parse_response(self, raw: str) -> EpisodeScript:
        """Extract JSON from Claude's response and build EpisodeScript."""
        # Find JSON block (Claude sometimes wraps in markdown)
        import re
        json_match = re.search(r"\{[\s\S]*\}", raw)
        if not json_match:
            raise ValueError("No JSON found in Claude response")

        data = json.loads(json_match.group(0))

        # Build scenes
        wpm = self._character.episode_format.get("words_per_minute", 140)
        scenes = []
        total_words = 0

        for s in data.get("scenes", []):
            narration = s.get("narration", "")
            words = len(narration.split())
            duration = round((words / wpm) * 60, 1)
            total_words += words
            scenes.append(
                Scene(
                    scene_number=s.get("scene_number", len(scenes) + 1),
                    title=s.get("title", f"Scene {len(scenes) + 1}"),
                    narration=narration,
                    visual_description=s.get("visual_description", ""),
                    emotion=s.get("emotion", "calm"),
                    duration_seconds=duration,
                    setting=s.get("setting", "The Sprawl"),
                    action=s.get("action", "standing"),
                )
            )

        total_duration = round((total_words / wpm) * 60, 1)

        return EpisodeScript(
            title=data.get("title", "Untitled Episode"),
            logline=data.get("logline", ""),
            theme=data.get("theme", ""),
            hook=data.get("hook", ""),
            scenes=scenes,
            call_to_action=data.get("call_to_action", ""),
            hashtags=data.get("hashtags", ["CaptainRaccoon"]),
            youtube_title=data.get("youtube_title", data.get("title", "")),
            youtube_description=data.get("youtube_description", ""),
            instagram_caption=data.get("instagram_caption", ""),
            total_duration_seconds=total_duration,
            word_count=total_words,
            raw_response=raw,
        )

    def _pick_random_topic(self) -> str:
        topics = [
            "when everything feels like too much",
            "the day I almost gave up",
            "why being small isn't a weakness",
            "the kindness that saved me",
            "how I found home in the strangest place",
            "what failure actually taught me",
            "why asking for help is brave",
            "the friend who changed everything",
            "starting over with nothing",
            "the quiet moments that matter most",
            "when nobody believed in me",
            "finding peace in the chaos",
            "the one thing I wish I'd known earlier",
            "why rest is not giving up",
            "being different in a world that wants same",
        ]
        return random.choice(topics)
